server:
    port: 8081
spring:
    application:
        name: gateway-service  
    cloud:
        consul:
            enabled: true
            host: localhost
            port: 8500
            discovery.acl-token: fcf8f0c8-2cb3-873f-43e5-b86618f8b8e1
            config:
                acl-token: fcf8f0c8-2cb3-873f-43e5-b86618f8b8e1
                enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            -   id: parameter-service-url
                uri: lb://parameter-service
                predicates:
                -   Path=/parameter/**
                filters:
                -   RewritePath=/parameter/(?<segment>.*), /$\{segment}
            -   id: common-service-url
                uri: lb://common-service
                predicates:
                -   Path=/common/**
                filters:
                -   RewritePath=/common/(?<segment>.*), /$\{segment}
            -   id: sbo-service-url
                uri: lb://sbo-service
                predicates:
                -   Path=/sbo/**
                filters:
                -   RewritePath=/sbo/(?<segment>.*), /$\{segment}
